### ISSUE TITLE
Android compatibility - javax.xml is not available

### ISSUE THREAD

**Issue by mahendranv** [mahendranv/anchor-rss#1]
Find alternative for XML stream reader to skip conflicting tags.

```
02-24 08:16:33.460 16835 16867 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLInputFactory;
02-24 08:16:33.460 16835 16867 E AndroidRuntime:        at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:115)
02-24 08:16:33.460 16835 16867 E AndroidRuntime:        at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:101)
02-24 08:16:33.460 16835 16867 E AndroidRuntime:        at com.fasterxml.jackson.dataformat.xml.XmlFactory.<init>(XmlFactory.java:85)
02-24 08:16:33.460 16835 16867 E AndroidRuntime:        at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:127)
02-24 08:16:33.460 16835 16867 E AndroidRuntime:        at com.github.mahendranv.AnchorParser.parse(AnchorParser.java:20)
```

**Comment by mahendranv** [comment]
Updated README for Android clients
